//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration_clients
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Clients
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string surName { get; set; }
        public string patronymic { get; set; }
        public int phoneNumber { get; set; }
        public string section { get; set; }
        public string passwrd { get; set; }
    }
}
